package com.babakids.app.audio

import android.content.Context
import com.babakids.app.data.ParentSettingsManager
import com.babakids.app.speech.SpeechHelper
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * The single entry point requested by the spec: playSmartVoice(text).
 *
 * Pipeline (fully offline, no network involved at any point):
 *   1. Bundled pre-generated audio (assets/audio/) — real pre-recorded
 *      clips shipped with the app. The *only* tier that can honestly
 *      claim a specific accent, since it's whatever voice actually
 *      recorded the clips. Ships empty by default (see
 *      BundledAudioManifest) until real .wav files are added.
 *   2. Local runtime cache — anything previously generated by tier 3.
 *   3. A real offline generation engine — not available in this build
 *      (see class doc below); this is the extension point for one later.
 *   4. Fallback — the device's built-in TTS (SpeechHelper). NOT confirmed
 *      to be Egyptian-accented; it's whatever voice pack the phone's TTS
 *      engine ships, most often generic/MSA-leaning Arabic. Used so the
 *      child never hears silence, but never mislabeled as "Egyptian" in
 *      logs or diagnostics.
 *
 * HONEST STATUS on tier 3: this build has no offline engine capable of
 * *generating new* Egyptian-Arabic audio at runtime. VoiceTut-TTS (a
 * Python/PyTorch-based model) can't run inside a compiled Android APK
 * without a substantial separate mobile-inference porting effort (ONNX
 * conversion, quantization, a mobile runtime) that isn't something this
 * environment can produce — there's no GPU or PyTorch toolchain available
 * here, and no access to that model's files. Per the spec's own fallback
 * instruction, this build uses tier 1 (bundled pre-generated audio)
 * instead — prepare real clips with any tool you have available (a voice
 * actor, VoiceTut/Sarah run externally, etc.) using
 * tools/generate_audio_manifest.py to get the exact filenames needed,
 * then drop them into assets/audio/.
 *
 * Also implements "prevent overlapping speech" (stops any current
 * playback before starting new speech) and respects Voice
 * Enabled/Volume from Parent Mode settings.
 */
class SmartVoiceManager private constructor(context: Context) {
    private val context = context.applicationContext
    private val cacheManager = AudioCacheManager(this.context)
    private val bundledManifest = BundledAudioManifest(this.context)
    private val player = AudioManager()
    private val speechHelper = SpeechHelper(this.context).also { it.init() }
    private val fallback = FallbackAudioManager(speechHelper)
    private val parentSettings = ParentSettingsManager(this.context)
    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    private val voice = "device_tts_fallback"
    private var lastSpokenText: String? = null
    private var lastSpokenEnglish: Boolean = false
    private var lastSpokenDialect: String = ParentSettingsManager.DIALECT_EGYPTIAN
    private var lastSpokenPitch: Float = 1f

    /**
     * Speaks `text` using the fastest available tier. Safe to call from
     * plain UI code — not a suspend function, everything happens
     * internally on a background dispatcher. `onResult` (optional) is how
     * the debug screen observes what actually happened. `onPlaybackComplete`
     * fires once the audio actually finishes playing (or fails) — used to
     * gate "wait until speaking is done" interactions, like not letting
     * the mic start listening while the word is still being spoken.
     */
    fun playSmartVoice(
        text: String,
        english: Boolean = false,
        dialect: String = ParentSettingsManager.DIALECT_EGYPTIAN,
        pitch: Float = 1f,
        onResult: (VoiceResult) -> Unit = {},
        onPlaybackComplete: () -> Unit = {}
    ) {
        if (text.isBlank()) {
            onPlaybackComplete()
            return
        }
        lastSpokenText = text
        lastSpokenEnglish = english
        lastSpokenDialect = dialect
        lastSpokenPitch = pitch

        scope.launch {
            val voiceEnabled = runCatching { parentSettings.voiceEnabledFlow.first() }.getOrDefault(true)
            if (!voiceEnabled) {
                VoiceDiagnostics.record("🔇 Voice is off in settings — skipping \"$text\"")
                report(onResult, VoiceResult.NOT_AVAILABLE)
                withContext(Dispatchers.Main) { onPlaybackComplete() }
                return@launch
            }
            val volume = runCatching { parentSettings.voiceVolumeFlow.first() }.getOrDefault(1f)

            withContext(Dispatchers.Main) { player.stopCurrentSpeech() }

            val normalized = TextNormalizer.normalize(text)
            val language = if (english) "en" else "ar"
            // The bundled VoiceTut clips and anything cached from them were
            // generated specifically for Egyptian colloquial Arabic — they
            // don't apply to English or Fusha (Modern Standard Arabic).
            // Only attempt tiers 1-2 when the parent has actually selected
            // Egyptian dialect; otherwise this behaves exactly like before
            // (straight to the device's own native/default-language TTS).
            val useVoiceTutTiers = !english && dialect == ParentSettingsManager.DIALECT_EGYPTIAN

            if (useVoiceTutTiers) {
                // Tier 1: bundled pre-generated audio, shipped with the app.
                val bundledRelativePath = bundledManifest.lookup(normalized)
                if (bundledRelativePath != null) {
                    VoiceDiagnostics.record("📦 Bundled audio hit for \"$text\"")
                    withContext(Dispatchers.Main) {
                        player.playAsset(
                            context,
                            bundledManifest.assetPathFor(bundledRelativePath),
                            volume = volume,
                            onComplete = onPlaybackComplete,
                            onFailure = {
                                VoiceDiagnostics.record("❌ Bundled file failed to play — using device TTS fallback")
                                fallback.speak(text, english, dialect, pitch, onDone = onPlaybackComplete)
                            }
                        )
                    }
                    report(onResult, VoiceResult.BUNDLED_HIT)
                    return@launch
                }

                // Tier 2: local runtime cache.
                val cacheKey = AudioCacheManager.computeCacheKey(normalized, language, dialect, voice)
                val cached = cacheManager.get(cacheKey)
                if (cached != null) {
                    VoiceDiagnostics.record("💾 Cache hit for \"$text\"")
                    withContext(Dispatchers.Main) {
                        player.playFile(
                            cached.filePath,
                            volume = volume,
                            onComplete = onPlaybackComplete,
                            onFailure = {
                                VoiceDiagnostics.record("❌ Cached file failed to play — using device TTS fallback")
                                fallback.speak(text, english, dialect, pitch, onDone = onPlaybackComplete)
                            }
                        )
                    }
                    report(onResult, VoiceResult.CACHE_HIT)
                    return@launch
                }
            }

            // Tier 3 (offline generation engine) intentionally has no
            // implementation to call here in this build — see class doc.

            // Tier 4: fallback — the device's own native/default-language
            // voice, exactly as it behaved before VoiceTut audio existed,
            // for English and Fusha (and for Egyptian when nothing bundled
            // or cached matched).
            VoiceDiagnostics.record(
                if (useVoiceTutTiers) {
                    "🔊 No bundled/cached audio for \"$text\" — device TTS fallback (not confirmed Egyptian)"
                } else {
                    "🌐 Not Egyptian dialect — using device's native-language TTS for \"$text\" (VoiceTut tiers skipped)"
                }
            )
            withContext(Dispatchers.Main) { fallback.speak(text, english, dialect, pitch, onDone = onPlaybackComplete) }
            report(onResult, VoiceResult.NOT_AVAILABLE)
        }
    }

    /** "Repeat Last Word" — re-plays whatever was last requested, if anything. */
    fun repeatLast(onResult: (VoiceResult) -> Unit = {}) {
        val text = lastSpokenText ?: return
        playSmartVoice(text, lastSpokenEnglish, lastSpokenDialect, lastSpokenPitch, onResult)
    }

    private suspend fun report(onResult: (VoiceResult) -> Unit, result: VoiceResult) {
        withContext(Dispatchers.Main) { onResult(result) }
    }

    fun bundledEntryCount(): Int = bundledManifest.entryCount()

    // Deliberately not a real teardown anymore — see companion object doc.
    // Kept as a no-op so existing call sites that still call it don't
    // break anything; the underlying TTS engine and player now live for
    // the whole app process, not any one screen.
    fun release() {}

    companion object {
        // A single shared instance for the whole app process, not one per
        // screen. This is the fix for a real bug: every screen used to
        // create its own SmartVoiceManager, each spinning up a brand new
        // TextToSpeech engine from scratch — TextToSpeech initialization
        // is asynchronous and genuinely takes real time (hundreds of
        // milliseconds on many devices), so a speak() call made right
        // after navigating to a new screen could easily fire before that
        // screen's freshly-created engine was ready, silently queuing (or
        // in the worst case losing) the utterance if the screen was left
        // again before the engine finished starting up. Reusing one
        // instance for the app's whole lifetime means the engine only
        // ever needs to become ready once.
        @Volatile private var instance: SmartVoiceManager? = null

        fun getInstance(context: Context): SmartVoiceManager {
            return instance ?: synchronized(this) {
                instance ?: SmartVoiceManager(context).also { instance = it }
            }
        }
    }
}
